stages:
  process_data:
    cmd: python src/process_data.py
    deps:
    - data/raw
    - src/main.py
    - src/process_data.py
    - config/main.yaml
    outs:
    - data/intermediate
    params:
    - params.yml
  segment:
    cmd: python src/segment.py
    deps:
    - data/intermediate
    - src/main.py
    - src/segment.py
    - config/main.yaml
    outs:
    - data/final
    - model/cluster.pkl
    metrics:
    - metrics.csv
    params:
    - params.yml
  analyze:
    cmd: jupyter notebook
    deps: 
    - notebook/analyze_data.ipynb
    - data/final

