stages:
  process_data:
    cmd: python src/process_data.py
    deps:
    - config/main.yaml
    - data/raw
    - params.yml
    - src/main.py
    - src/process_data.py
    outs:
    - data/intermediate:
        cache: false
  segment:
    cmd: python src/segment.py
    deps:
    - config/main.yaml
    - data/intermediate
    - params.yml
    - src/main.py
    - src/segment.py
    outs:
    - data/final:
        cache: false
    - image:
        cache: false
    - model/cluster.pkl:
        cache: false
    metrics:
    - metrics.csv:
        cache: false
  analyze:
    cmd: jupyter notebook
    deps:
    - notebook/analyze_data.ipynb
    - data/final

