stages:
  process_data:
    cmd: python src/main.py flow=process_data
    deps:
    - config/main.yaml
    - data/raw
    - params.yml
    - src/main.py
    - src/process_data.py
    outs:
    - data/intermediate:
        cache: false
        persist: true
  segment:
    cmd: python src/main.py flow=segment
    deps:
    - config/main.yaml
    - data/intermediate
    - params.yml
    - src/main.py
    - src/segment.py
    outs:
    - data/final:
        cache: false
        persist: true
    - image:
        cache: false
        persist: true
    - model/cluster.pkl:
        cache: false
        persist: true
    metrics:
    - metrics.csv:
        cache: false
        persist: true
  analyze:
    cmd: python src/main.py flow=run_notebook
    deps:
    - notebook/analyze_data.ipynb
    - data/final

