family_size: '{''Married'': 2, ''Together'': 2, ''Absurd'': 1, ''Widow'': 1, ''YOLO'':
  1, ''Divorced'': 1, ''Single'': 1, ''Alone'': 1}'
keep_columns: '[''Income'', ''Recency'', ''NumWebVisitsMonth'', ''Complain'', ''age'',
  ''total_purchases'', ''enrollment_years'', ''family_size'']'
model:
  algorithm: auto
  copy_x: true
  init: k-means++
  max_iter: 300
  n_clusters: '4'
  n_init: 10
  random_state: null
  tol: 0.0001
  verbose: 0
model_class: KMeans
name: process_2
num_columns: 8
remove_outliers_threshold: '{''age'': 90, ''Income'': 600000}'
