
hydra:  
  output_subdir: null  
  run:  
    dir: .

flow: all 

raw_data: 
  path: data/raw/marketing_campaign.csv

intermediate:
  dir: data/intermediate
  name: scale_features.csv
  path: ${intermediate.dir}/${intermediate.name}

final:
  dir: data/final
  name: segmented.csv
  path: ${final.dir}/${final.name}

image:
  kmeans: image/elbow.png
  clusters: image/cluster.png

model:
  path: model/cluster.pkl

process:
  keep_columns:
    - Income
    - Recency
    - NumWebVisitsMonth
    - Complain
    - age
    - total_purchases
    - enrollment_years
    - family_size

  remove_outliers_threshold:
    age: 90
    Income: 600000

  family_size:
    Married: 2
    Together: 2
    Absurd: 1
    Widow: 1
    YOLO: 1
    Divorced: 1
    Single: 1
    Alone: 1

